{{- if and .Values.web.enabled .Values.web.ingress.enabled -}}
{{- $svc := include "muninn.web.fullname" . -}}
{{- $port := .Values.web.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "muninn.web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "muninn.web.labels" . | nindent 4 }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.web.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.web.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.web.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $svc }}
                port:
                  number: {{ $port }}
          {{- end }}
    {{- end }}
{{- end }}
