apiVersion: muninn.io/v1beta1
kind: HuginnIssue
metadata:
  labels:
    app.kubernetes.io/name: huginnoperator
    app.kubernetes.io/managed-by: kustomize
  name: huginnissue-sample
spec:
  # TODO(user): Add fields here
